### PR TITLE
feat(trading): add asset activity table

### LINKED ISSUE #6101: Transaction list in portfolio
## Story

As a user
I want to see a full list of transactions I have made
So that I know what I have done

## Acceptance Criteria

Note; this ticket is a stepping stone to a large rework of the portfolio page, but for now we will aim to create the transaction list simply in teh current AG grid structure.  After this we can move it into the new design Joelle is working on.

- [x] Modify the Collateral / Deposits / Withdrawals table in Portfolio to be Collateral & Transaction List, where this list combines all of deposits, transfers and withdrawals into a single structure
- [x] Need a way to fetxh some number of deposits, withdrawals and transfers for the connected key and order them by timestamp descending, such that we can load more if needed and dont lose any rows
- [x] A list of all transactions showing the following columns
  - [x] Type (deposit, transfer in, transfer out, withdrawal)
  - [x] Asset code (looked up from assets API)
  - [x] Datetime
  - [x] Amount (converted with asset decimals from assets API)
  - [x] To / From
  - [x] Status 
- [x] To / From field will be conditional
  - [x] For deposit it will always be the source ERC20 address
  - [x] For transfer TO the current key show the sender Vega key
  - [x] For transfer FROM the current key show the recipient Vega key
  - [x] For withdrawal show the ERC20 address
- [ ] Status will also be conditional
  - [x] For deposit: 
    - [x] Show "Pending (X / Y Confirmations)" 
    - [x] Then show "Complete"
  - [x] For withdrawal
    - [ ] ~~Show "Pending - approve in wallet" while waiting for wallet~~ N/A
    - [x] Then "Pending - sent from network" once a txHash is available
    - [x] Then "Complete - received on target network" once a ref is available (i think)
  - [x] For transfer 
    - [ ] ~~Show "Pending - approve in wallet" while waiting for wallet~~ N/A
    - [x] Then "Complete" once done ... dont think it is worth an interim message when its so fast
- [x] Should be possible to filter on the type to view only deposits / transfer / withdrawals
- [x] There is currently a consditional "deposit" and "make withdrawal" button .... remove these since there will be a new panel due to #6267 
- [x] Make sure we are showing all withdrawals correctly; there is a suspision in mainnet currently that we're doing something wrong here and hence not showing failed withdrawals ... but with extra Console validation now its very hard to verify this 
  - [x] Must ensure if there are STATUS_REJECTED withdrawals we are showing them... this might mean we need to be able to sign withdrawals under the required minimum and send them so Core fails them instead of Console / VegaWallet
  - [x] Must ensure we're showing STATUS_OPEN withdrawals when they appear ... this will be very brief since it only lasts the time it takes the validators to process, but we need to show it
  - [x] If it is STATUS_FINALISED and there is no txHash that means it has not been finalised on ethereum and we need to show a status for this, and a prompt to "Complete withdrawal"
  - [x] IF it is STATUS_FINALISED and has a txHash then it is fully complete
- [x] Ensure that transfers both TO and FROM are shown
- [x] Ensure that pending and failed / rejected withdrawals are shown
- [x] Show the chain name in brackets after the asset code
- [x] If there are incomplete withdrawals 
  - [x] We should pin these to the top of the list and potentially highlight them in some way
  - [x] We should add some sort of indicator to the menu to highlight the Portfolio page in the nav so they know to go there and complete it.

## Sketch

Suggest the easiest way to initially build this thing is to enhance the current table which shows collateral / deposits / withdrawals

That way we can do the backend work and just dump it into new tabe here. 

Image

Then in the long term Joelle is doing a redesign of this page to land on somethign more like the below.

image

## Additional details / background info

Summary of logic:

image

### PR DESCRIPTION
**Pull request by mattrussell36**
# Related issues 🔗

Closes #6101 

# Description ℹ️

- Removes deposits and withdrawals tabs
- Adds asset activity tab for viewing all deposits/withdraws and transfers
- Moves withdrawals indicator to the main navbar

# Demo 📺

Screenshot 2024-07-22 at 16 59 05

Screenshot 2024-07-22 at 16 55 33

### CODE REVIEW

**Comment by JonRay15** [comment]
Feedback 1:

The updates arent very smooth.  I have done a transfer and can already see on explorer that it is complete, but the page hasnt updated. 

image

And after a refresh 

image

**Comment by JonRay15** [comment]
Feedback 2:

ON transfers

I sent a tranfer of 100 USDT from my main testnet address (89fd87b86727fa4d9ab06b9f4e64b51c9b07055e8a0c8f0bc40f0a249e321525) to one of my other ones (3fc24730cad7d22f27244d1c8959135dc71becbfcbf86ac0a3a76622300f86c9)

It says it is TO 89fd87b86727fa4d9ab06b9f4e64b51c9b07055e8a0c8f0bc40f0a249e321525 which is MY address. 

It should be showing "To: 3fc24730cad7d22f27244d1c8959135dc71becbfcbf86ac0a3a76622300f86c9"

image

I get the same thing when I try to send the funds back from 3fc TO 89f ....

image


Also I think we shoulld change type to be a little clearer.  The to / from section can stay unchanged.
"Transfer from" >> "Transfer received"
"Transfer to" >> "Transfer sent"

**Comment by JonRay15** [comment]
Feedback 3:

Withdrawals the error code when you try to withdraw before the withdrawal is ready could be made more user friendly.  This is back to that plan we had to start building a store of codes with mappings to nicer human-readable explanations.  Not sure where we got with that.

image

**Comment by JonRay15** [comment]
Feedback 4: 

I feel like swaps shoudl be in here ... but thats on another ticket so ignore for now!

**Review by edd — APPROVED** [review]

**Comment by JonRay15** [comment]
All this now works ... but still not sure about withdrawals.

Not sure I like this 

image

I think "Connect" should be "Complete" ... and then if you need to connect it connects you.

**Comment by JonRay15** [comment]
I also think the pinned rows could look a bit more obvious.... make it a bit clearer there is action required on them.  Maybe blue highighting to match the button?  Or a blue border?  Or just a thicker line?  Soomething ... 

image

**Pull request merged**
