### PR TITLE
chore(trading): referrals text and ui tweaks, bug fixes

### LINKED ISSUE #5144: Review and finalise all words on the referrals page with legal
## The Chore

The text is a bit rubbish currently ... and needs legal signoff. Write it with Dave.

## Tasks

- [ ] Test on the landing page before any codes are applied
- [ ] Text when you have created a code
- [ ] Text when you have applied a code

### LINKED ISSUE #5176: Improve handling when no current referral program
## The Chore

Currently the handling for no active programs is a little flaky. 

It will let you try to create a code, and then the screen stays unchanged, it doesnt flip to some reduced version of the stats page, it just goes back to teling you you can ctreate a code. 

## Tasks

- [x] Add an extra check when someone creates a code to see if there is a program active.  
  - [x] If there is no program display an extra step in the modal to say "There is currently no referral program active, are you sure you want to create a code?"
  - [x] If they click yes, it should continue the flow as normal
- [x] Once they create the code the screen should change to the referrer stats page which should keep certain bits and replace others with a "No active programs" text
- [x] We should also change that text at the bottom a bit. We're not "sorry" ... :) ... change text to the below: 

There are currently no active referral programs. 
Check the [Governance App](https://governance.vega.xyz/proposals) to see if there are any proposals in progress and vote.
You can propose a new program via the [Docs](https://docs.vega.xyz/mainnet/tutorials/proposals/referral-program-proposal).

## Additional details / background info

Sketch below

image

### LINKED ISSUE #5298: Ensure onboarding journey via referral link is smooth
## The Chore

Need to review the onboarding flow for cases when a user is landing on the site via a referral link.

I will list in full the ACs that I think we need to cover based on discussion, though some of these may already be covered by existing functionality.

## Acceptance Criteria

- [x] User can be sent a link with a referral code embedded in it (#5220)
- [x] When user navigates to that link they reach the referrals page with the form pre-filled
- [x] User sees a preview of the set they are joining
- [x] If user already has a wallet with funds
  - [x] User can click apply and be added to the set
- [ ] If user has wallet but no funds
  - [x] App should check for funds when the code is filled in, ie. at the same time as generating the preview below
  - [x] Display message under the "Apply a code" button saying "Require minimum of `spam.protection.applyReferral.min.funds` to join a referral set to protect the network from spam."
  - [x] Change button to "Deposit funds" 
  - [x] If clicked, button should pop out the deposit sidebar so the user can complete their deposit
  - [x] Once the deposit has been completed, the check needs to refresh so that button updates without any janky refresh needed
- [x] If user has no wallet 
  - [x] Button should display "Connect wallet" and launch the usual onboarding / download process (which it already does, just leaving this here for completeness)

### Extra info on insufficient funds

Current behaviour is there is no check for funds.  The user can try to apply the code and will be asked to approve the TX in their wallet.  The transaction will then fail, and the error reason is not passed back via the wallet very well. 

Current view when trying to join set from a key with no funds `3fc24730cad7d22f27244d1c8959135dc71becbfcbf86ac0a3a76622300f86c9`. 

image

I then tried to join the same code from `099c59484e4a0db12d06dc52cb57f4c0e0b861a90d70d7afdfe6cd8e88d94612` (which has funds) and was successful so I'm fairly confident it is that.

### LINKED ISSUE #5399: Volume and Epochs to next tier no longer populating in referrals view
## Description

In the referrals view, 'volume to next tier' and 'epochs to next tier' remain at zero, regardless of trades placed and epochs in set. See example below:
image
**Epochs to next tier:** In the above screenshot, I have two epochs in my set and I am in tier 2. Therefore the epochs to next tier value should be 1, given the next tier is tier 3 and Min epochs is set to 3 for this tier.

**Volume to next tier**: In the above screenshot, you can see that the 'combined running notional over the 1 epoch' (I think we should adjust the wording here!) is 221, so volume to next tier should be 79 given that the volume required for the next tier is 300, it is currently 0. 

## Steps to Reproduce

1. Go to referrals e2e test (Referrals/test_referrals.py) https://github.com/vegaprotocol/frontend-monorepo/pull/5349
2. comment out the assertions in the check_tile_values method
3. put a page.pause() inside check_tile_values _after_ the initial navigation to referrals
4. run the test `poetry run pytest -k "test_referral" -s --headed`
5. Observe at each pause the mentioned values remain at zero

## Expected behavior

Volume and epochs to next tier update corresponding to volume traded and number of epochs in set

- Browser: chrome

### PR DESCRIPTION
**Pull request by asiaznik**
# Related issues 🔗

Closes #5144
Closes #5176
Closes #5399 
Closes #5298 

# Description ℹ️

* changes texts
* updates UI for tiers
* fixes "next tier" issue
* adds min funds spam protection as per 5298

# Demo 📺

Screenshot 2023-11-30 at 21 02 51

# Technical 👨‍🔧

N/A

### CODE REVIEW

**Review by MadalinaRaicu — APPROVED** [review]

**Review by guoguojin — APPROVED** [review]

**Comment by JonRay15** [comment]
Created this ticket for the bug on the referree volume. 

https://github.com/vegaprotocol/frontend-monorepo/issues/5457

**Comment by candida-d** [comment]
> "There are currently no active referral programs. Check the Governance App to see if there are any proposals in progress and vote. You can propose a new program via the Docs." nit - Docs should be a lower case 'd'
> 
Proposed alternative change: Instead of "You can propose a new program via the Docs." How about "Use the docs tutorial  to propose a new program."

**Comment by JonRay15** [comment]
How it works = fine
Title and strapline = fine
New tiles = look good

The stuff with no current progam I cant test cos need the setup, same for looking at 6 tiers.  Need @dalebennett1992

**Comment by dalebennett1992** [comment]
I know this is a quick fix so I am assuming fine for now, but the accessibility police would arrest us for this
image

**Review by bwallacee — APPROVED** [review]

**Pull request merged**
