### PR TITLE
fix(trading): referee tier statistic

### PR DESCRIPTION
**Pull request by asiaznik**
# Related issues 🔗

Related #5746 

# Description ℹ️

* fixes tier statistics

# Demo 📺

N/A

# Technical 👨‍🔧

N/A

### CODE REVIEW

**Comment by JonRay15** [comment]
Sorry bad news on this ... I dont think we want to merge it. 

We just noticed some behaviour in mainnet that it is possible to join a team without getting its referral benefits....and apparently we think that is correct and desirable.... therefore we think that showing the referral benefits associated to a team is not the right thing to do.  Sorry @asiaznik ... 🙈

**Review by JonRay15 — CHANGES_REQUESTED** [review]
See comment .... based on discussion literally just now with Barney and Charlie we dont think we should do this ... sorry.

**Comment by asiaznik** [comment]
Remove the part that displayed the tiles on a team page and left the fix in.

**Review by mattrussell36 — APPROVED** [review]

**Review by JonRay15 — APPROVED** [review]

**Pull request merged**
