### PR TITLE
feat(trading): mobile layout and buttons

### LINKED ISSUE #5741: Console Mobile CTA BUTTONS instead of sidebar
## Task

Add/modify our bottom actions (sidebar when horizontal) to have clear CTAs to trade (IE make it super clear how to get to the deal ticket)

## User story

_As a_ user
_I want to_ use console on mobile 
_So that_ I can connect my wallet, trade on my phone, and view my positions

## Acceptance criteria

- [ ] Add/modify our bottom actions (sidebar when horizontal) to have clear CTAs to trade (IE make it super clear how to get to the deal ticket)

## Sketch

mobile

### PR DESCRIPTION
**Pull request by MadalinaRaicu**
# Related issues 🔗

Closes #5741 

# Description ℹ️

Adds new mobile CTA buttons 

# Demo 📺

Screenshot 2024-02-06 at 14 25 01
Screenshot 2024-02-06 at 14 25 18
Screenshot 2024-02-06 at 14 25 18

# Technical 👨‍🔧

Details of technical implementation that reviewers may need to be aware of, if applicable.

### CODE REVIEW

**Comment by bwallacee** [comment]
@MadalinaRaicu it took me a while to work out what this button actually does:
image
I'm not sure it makes sense or maybe it needs a new icon.

**Comment by MadalinaRaicu** [comment]
> @MadalinaRaicu it took me a while to work out what this button actually does: 

Totally agree! I have just done a change and I think it's better

**Comment by bwallacee** [comment]
@MadalinaRaicu sorry i should have noticied before.
Could we change this text to be white or a lighter grey(in dark mode) and maybe black / dark grey in light mode:
image

image
Also there is no highlight on selected in dark mode:
image
image

**Comment by mattrussell36** [comment]
@MadalinaRaicu @bwallacee looks a little wierd on other pages now

Screenshot 2024-02-06 at 19 51 39

**Comment by bwallacee** [comment]
@MadalinaRaicu would it make sense to update these buttons to match the trading pages:
image

**Comment by MadalinaRaicu** [comment]
> @MadalinaRaicu would it make sense to update these buttons to match the trading pages: 

sure can. updated. 
Screenshot 2024-02-08 at 13 35 24

Screenshot 2024-02-08 at 13 35 33

**Review by bwallacee — APPROVED** [review]
Approved, although the on hover for the back button is maybe a bit pointless as it can't be seen on mobile.

Also it says back to chart, although it might not take you back to chart it might take you back to competitions page etc.

**Comment by MadalinaRaicu** [comment]
> Approved, although the on hover for the back button is maybe a bit pointless as it can't be seen on mobile.
> 
> Also it says back to chart, although it might not take you back to chart it might take you back to competitions page etc.

I agree, I have renamed it to "Back"

**Pull request merged**
