### PR TITLE
feat(trading): market icons in console

### LINKED ISSUE #5096: Add icons for markets
## Story

As a user
I want to be able to see nice icons in Console for markets and assets
So that I think "wow ... Console looks cool"

## Acceptance Criteria

- [ ] Show in market header for current market
- [ ] Show in the market selector
- [x] Show in the markets page

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

### PR DESCRIPTION
**Pull request by MadalinaRaicu**
# Related issues 🔗

Closes #5096 

# Description ℹ️

Add icons for markets in console. 

# Demo 📺

Screenshot 2024-04-23 at 11 09 30
Screenshot 2024-04-23 at 11 07 30
Screenshot 2024-04-23 at 11 03 22
Screenshot 2024-04-23 at 11 04 46

# Technical 👨‍🔧

Details of technical implementation that reviewers may need to be aware of, if applicable.

### CODE REVIEW

**Review by edd — APPROVED** [review]
Two notes, neither blocking or requiring changes:

1. It's possible to use `Emblem` and have that component determine that it's a market component, and then render `EmblemByMarket`. There's no advantage to that, it's just the pattern I've used. 
2. `explorer` uses the point above to make another wrapper component, `EmblemWithChain`, that avoids the repeated need to import `Emblem` as well as `useVegaChain`. Again, though, that's just convenience. What you've done is also valid

One last point - the fact that the two icons are not aligned vertically is more of a mistake than an intentional design fix. I guess we might change this separately when/if someone requests it. On the other hand: it looks fine.

**Comment by JonRay15** [comment]
I dont love the vertical offset here.

I feel like there needs to be a less horizontal overlap and they should be at the same height.

image

**Comment by MadalinaRaicu** [comment]
> I dont love the vertical offset here.
> I feel like there needs to be a less horizontal overlap and they should be at the same height.
> Also when we start adding that third icon to denote the chain it will be a problem if we dont do the above.

> One last point - the fact that the two icons are not aligned vertically is more of a mistake than an intentional design fix. I guess we might change this separately when/if someone requests it. On the other hand: it looks fine.


I will fix the vertical offset in the emblem icon component, that should fix it everywhere. Initially, I thought that was done on purpose, but I will change that. 

The third icon (chain) will be added in another PR because we don't know yet how to get the proper `chain icon`  and it is in prog here: https://vegaprotocol.slack.com/archives/C8WS7M50E/p1713540865169819

**Review by bwallacee — APPROVED** [review]
We are missing the white outlines on the Icons, but approved so we can get in for the incentive.

**Pull request merged**
