### PR TITLE
feat(trading): show current epoch progress bar on rewards page trading

### LINKED ISSUE #5813: Add an epoch counter to the reward page
## The Chore

I have to keep going to the Governance site reward page to see what epoch we're in and when the next one ends. 

This is rubbish.

We need to find a home for it on the rewards / competitions page somewhere.

We have a component in governance we could steal 

Image

Maybe play with finding a home for it

## Tasks

- [ ]
- [ ]

### PR DESCRIPTION
**Pull request by MadalinaRaicu**
# Related issues 🔗

Closes #5813 

# Description ℹ️

- [x] Add an epoch counter to the reward page
- [x] Re-use component from governance, added to ui-toolkit

# Demo 📺

Screenshot 2024-04-04 at 11 16 13

# Technical 👨‍🔧

Details of technical implementation that reviewers may need to be aware of, if applicable.

### CODE REVIEW

**Comment by mattrussell36** [comment]
I'm not sure this is the best spot for it. I think it needs to be more prominent, perhaps right under the main page header with 1/3 the width so it aligns with the grid below

**Comment by MadalinaRaicu** [comment]
> @MadalinaRaicu I'm not sure this is the best spot for it. I think it needs to be more prominent, perhaps right under the main page header with 1/3 the width so it aligns with the grid below

This is how it looks with full width and 1/3 width, let me know what you prefer. 

Screenshot 2024-03-28 at 13 57 16

image

**Review by wwestgarth — APPROVED** [review]

**Review by bwallacee — APPROVED** [review]

**Comment by JonRay15** [comment]
Can we just simplify this to something like this?

This whole component just seems entirely overengineered from ages ago.  Its an epoch, and a time remaining.  It doesnt need a giant progress bar! 😂 

image

**Comment by JonRay15** [comment]
Something like this would be another option .... but that also feels too much cos it introduces a new tile outside of structure. 

So I prefer the first one where its just text, no tiles to muddy the water?

image

**Comment by MadalinaRaicu** [comment]
> Something like this would be another option .... but that also feels too much cos it introduces a new tile outside of structure.
> 
> So I prefer the first one where its just text, no tiles to muddy the water?
> 
> image

updated 

Screenshot 2024-04-04 at 11 16 13

**Pull request merged**
